### añadir nueva planta
POST http://localhost:5000/plantas HTTP/1.1
content-type: application/json

{
    "Nombre": "Planta 1",
	"Referencia": "Esta planta da risa",
	"Tamaño": 1.20,
	"Stock": 8,
	"Activo": true,
	"Tipo": "Oregano",
	"Precio": 2.50,
	"Foto": "FOTO"
}
### añadir nueva planta heroku
POST http://localhost:5000/plantas HTTP/1.1
content-type: application/json

{
    "Nombre": "Planta 2",
	"Referencia": "Esta planta da risa",
	"Tamaño": "1.20",
	"Stock": 8,
	"Activo": true,
	"Tipo": "Oregano",
	"Precio": 2.50,
	"Foto": ["FOTO", "publicID"]
}

### Obtener todas las plantas
GET http://localhost:5000/plantas/

### Buscar planta por nombre
GET http://localhost:5000/plantas/Planta 1

### Eliminar planta
DELETE http://localhost:5000/plantas/eliminar/616ae392d6248417620c093b HTTP/1.1

### Cambiar estado activo
GET http://localhost:5000/plantas/activo/6165abbf5357ffcb01aeff98

### Cambiar estado activo
GET https://blomia.herokuapp.com/plantas/activo/6169d23e1e3a3da220c09867

### modificar
patch http://localhost:5000/plantas/modificar/616ae5baf29f3387eaec5fb7 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjYxNmRiNzMxNjczNGNjNDA2M2JiNzM4YiIsIk5vbWJyZSI6ImFkbWluIiwiaWF0IjoxNjM0NTg1OTMzLCJleHAiOjE2MzQ2MDc1MzN9.zCfu0T4GsIQnDMDRyLvI_FA9l4GK4c2KvJPzR3Vjv70

{
	"Precio": [1000]
}
### modificar
patch https://blomia.herokuapp.com/plantas/modificar/616ae5baf29f3387eaec5fb7 HTTP/1.1
content-type: application/json

{
"Precio": [0.99]
}
###	"Precio": [2.50,10,11,13]

### modificar
patch http://blomia.herokuapp.com/plantas/stock/616ae5baf29f3387eaec5fb7 HTTP/1.1
content-type: application/json

{
	"Stock": 2500
}